### ISSUE TITLE
Need an CONTRIBUTING.md

### ISSUE THREAD

**Issue by adi0311** [adi0311/firstRepository#2]
The file should describe name convention for files, folders, functions, classes and variable names.

**Comment by satyabansahoo2000** [comment]
@adi0311 Assign it to me.

**Comment by adi0311** [comment]
Go ahead!!

**Comment by satyabansahoo2000** [comment]
[contribution.md #4 ](https://github.com/adi0311/Data-Structures-and-Algorithms-in-Python/pull/4)
If any changes needed, please mention it.

**Comment by adi0311** [comment]
Can you please change the name of the file to CONTRIBUTING.md (case sensitive)

**Comment by hemraj4545** [comment]
@adi0311 sure

**Comment by satyabansahoo2000** [comment]
@adi0311 done the changes.

**Comment by adi0311** [comment]
Thanks for your contribution!
