### ISSUE TITLE
Add Missing Data Structures and Algorithms

### ISSUE THREAD

**Issue by adi0311** [adi0311/firstRepository#5]
Feel free to add any Data Structure or Algorithm which are yet not present in the repository. If the code is already present or is in some other language or is incorrect, it will be marked as spam.

**Comment by Jeewantha-Madubashana** [comment]
Hi, I would like to work on this feature. Please assign it to me.

**Comment by adi0311** [comment]
Go ahead!

**Comment by Jeewantha-Madubashana** [comment]
@adi0311  I created full request for the issue. please review
